name: deploy

on:
  push:
    branches: [main] # Workflow is triggered when you push to these branches
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04 # ex) EC2 instance

    strategy:
      matrix:
        node-version: [14.21.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # What you will do after (repository code -> CI server)
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} # install Node.js with the version you wrote above
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo NODE_SERVER_PORT=${{ secrets.NODE_SERVER_PORT }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo HTTPS_PORT=${{ secrets.HTTPS_PORT }} >> .env
          echo HTTP_PORT=${{ secrets.HTTP_PORT }} >> .env
          echo RDS_HOST=${{ secrets.RDS_HOST }} >> .env
          echo RDS_PORT=${{ secrets.RDS_PORT }} >> .env
          echo RDS_USERNAME=${{ secrets.RDS_USERNAME }} >> .env
          echo RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} >> .env
          echo RDS_DATABASE_NAME=${{ secrets.RDS_DATABASE_NAME }} >> .env
          cat .env

      - name: build server files
        working-directory: ./
        run: |
          yarn
          yarn run build

      ################## CD 구축 단계에서 추가 부분

      # 리포지토리 압축
      - name: zip file
        # run: zip -r pyramid.zip ./dist ./scripts ./appspec.yml ./.env ./package.json
        # run: zip -r pyramid.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*" # node_module 등 파일들은 제외한 나머지 모두 압축
        # test 005
        # run: zip -r pyramid.zip . ./dist ./src ./test -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*"
        # test 006
        run: zip -r pyramid.zip ./dist ./scripts ./src ./test ./.env ./appspec.yml ./nest-cli.json ./package-lock.json ./package.json ./tsconfig.build.json ./tsconfig.json ./ -x "node_modules/*" "coverage/*" "*.git*"

      # S3 접근을 위한 IAM 사용자 키값등록
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # S3에 압축 파일을 옮겨줌
      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./pyramid.zip s3://pyramid-build/deploy/

      # AWS CodeDeploy 실행 시 가장 아랫줄 지정한 곳에 압축 파일 푼 뒤, CodeDeploy와 연결된 EC2 인스턴스에 배포
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name pyramid-test-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name GROUP
          --s3-location bucket=pyramid-build,bundleType=zip,key=deploy/pyramid.zip

      # 배포 완료 후 after-deploy.sh 저장한 명령어들이 실행되면서 서버 자동 재시작
